# mysql:
#     image: mysql:5.7.11
#     environment:
#         - MYSQL_ROOT_PASSWORD=root
apache-php:
    image: php:5.6.19-apache
    ports:
        - "1080:80"
    volumes:
        - .:/var/www/html
        - /Users/toukubo/Dropbox/nodes/inbox/management.run/#due:/data
    # links:
        # - mysql:db
# phpmyadmin:
#     image: phpmyadmin/phpmyadmin:4.5.3.1-1
#     ports:
#         - "18080:8080"
    # links:
    #     - mysql:db

